-- Drop table APPEARS
DROP TABLE APPEARS CASCADE CONSTRAINTS;

-- Drop table DOCUMENT
DROP TABLE DOCUMENT CASCADE CONSTRAINTS;

-- Drop table TERM
DROP TABLE TERM CASCADE CONSTRAINTS;

-- Drop table SOURCE
DROP TABLE SOURCE CASCADE CONSTRAINTS;

-- Drop table DOCUMENT_STATS
DROP TABLE DOCUMENT_STATISTICS CASCADE CONSTRAINTS;